baseURL = "http://aclweb.org/anthology/"
languageCode = "en-us"
title = "ACL Anthology"
disablePathToLower = true
staticDir = ["static", "data-export"]


[menu]

  [[menu.footer]]
    identifier = "queue"
    name = "Ingestion Queue"
    url = "http://bit.ly/aclAnthologyQ"

  [[menu.footer]]
    identifier = "issues"
    name = "Issues"
    url = "https://github.com/acl-org/acl-anthology/issues/"
